name: BumpStdlibs
on:
  workflow_dispatch:
    inputs:
      BUMPSTDLIBS_STDLIBS_TO_INCLUDE:
        description: 'Comma-separated list of stdlibs to include like "Pkg,Downloads", or "all" for all:'
        required: false
        default: 'all'
      BUMPSTDLIBS_CLOSE_OLD_PULL_REQUESTS:
        description: 'Close outdated pull requests: (true/false)'
        required: false
        default: 'true'
      BUMPSTDLIBS_PUSH_IF_NO_CHANGES:
        description: 'Push (and retrigger CI) even if there are no changes: (true/false)'
        required: false
        default: 'false'
jobs:
  BumpStdlibs:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "BUMPSTDLIBS_STDLIBS_TO_INCLUDE is ${{ github.event.inputs.BUMPSTDLIBS_STDLIBS_TO_INCLUDE }}"
      - run: git config --global user.name "Dilum Aluthge"
      - run: git config --global user.email "dilum@aluthge.com"
      - run: julia --color=yes --project -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'
      - run: julia --color=yes --project -e 'using BumpStdlibs; bump_stdlibs("JuliaLang/julia")'
        env:
          BUMPSTDLIBS_CLOSE_OLD_PULL_REQUESTS: ${{ github.event.inputs.BUMPSTDLIBS_CLOSE_OLD_PULL_REQUESTS }}
          BUMPSTDLIBS_PUSH_IF_NO_CHANGES: ${{ github.event.inputs.BUMPSTDLIBS_PUSH_IF_NO_CHANGES }}
          BUMPSTDLIBS_STDLIBS_TO_INCLUDE: ${{ github.event.inputs.BUMPSTDLIBS_STDLIBS_TO_INCLUDE }}
          BUMPSTDLIBS_TOKEN: ${{ secrets.BUMPSTDLIBS_TOKEN }}
          BUMPSTDLIBS_SENDER: ${{ github.event.sender.login }}
          JULIA_DEBUG: 'all'
