name: BumpStdlibs
on:
  workflow_dispatch:
    inputs:
      BUMPSTDLIBS_TARGET_BRANCH:
        description: 'Target branch (in the JuliaLang/julia) to target. Examples include master, backports-release-1.9, etc.'
        required: true
        default: 'master'
      BUMPSTDLIBS_STDLIBS_TO_INCLUDE:
        description: 'Comma-separated list of stdlibs to include like "Pkg,Downloads", or "all" for all:'
        required: true
        default: 'all'
      BUMPSTDLIBS_CLOSE_OLD_PULL_REQUESTS:
        description: 'Close outdated pull requests. Default: yes'
        type: boolean
        required: true
        default: true
      BUMPSTDLIBS_PUSH_IF_NO_CHANGES:
        description: 'Push (and retrigger CI) even if there are no changes. Default: no'
        type: boolean
        required: true
        default: false
jobs:
  BumpStdlibs:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "BUMPSTDLIBS_STDLIBS_TO_INCLUDE is ${{ github.event.inputs.BUMPSTDLIBS_STDLIBS_TO_INCLUDE }}"
      - run: git config --global user.name "Dilum Aluthge"
      - run: git config --global user.email "dilum@aluthge.com"
      - run: julia --color=yes --project -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'
      - run: julia --color=yes --project -e 'using BumpStdlibs; bump_stdlibs("JuliaLang/julia")'
        env:
          BUMPSTDLIBS_CLOSE_OLD_PULL_REQUESTS: ${{ github.event.inputs.BUMPSTDLIBS_CLOSE_OLD_PULL_REQUESTS }}
          BUMPSTDLIBS_PUSH_IF_NO_CHANGES: ${{ github.event.inputs.BUMPSTDLIBS_PUSH_IF_NO_CHANGES }}
          BUMPSTDLIBS_SENDER: ${{ github.event.sender.login }}
          BUMPSTDLIBS_STDLIBS_TO_INCLUDE: ${{ github.event.inputs.BUMPSTDLIBS_STDLIBS_TO_INCLUDE }}
          BUMPSTDLIBS_TARGET_BRANCH: ${{ github.event.inputs.BUMPSTDLIBS_TARGET_BRANCH }}
          BUMPSTDLIBS_TOKEN: ${{ secrets.BUMPSTDLIBS_TOKEN }}
          JULIA_DEBUG: 'all'
